---
sudo: required

services:
  - docker

env:
  global:
    - distribution: docker-stack
    - container_id: docker-stack-container
    - container_user: scientist

before_install:
  - 'sudo docker build --no-cache --rm --file=Dockerfile --tag=${distribution}:latest .'

script:
  - 'sudo docker run --name ${container_id} --detach --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro ${distribution}:latest'
  - 'sudo docker exec --user ${container_user} "${container_id}" verdi calculation plugins'
  - 'sudo docker exec --user ${container_user} "${container_id}" verdi daemon status'

